from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('schedule/', views.schedule, name='schedule'),
    path('gallery/', views.gallery, name='gallery'),
    path('blog/', views.blog, name='blog'),
    path('blog/<int:post_id>/', views.blog_detail, name='blog_detail'),
    path('blog_details/', views.blog_details, name='blog_details'),
    path('elements/', views.elements, name='elements'),
    path('contact/', views.contact, name='contact'),
    path('form/', views.form, name='form'),
    path('myadmin/', views.admin_login, name='admin_login'),
    path('customers/', views.customer_list, name='customer_list'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('add-user/', views.add_user, name='add_user'),
    path('fee-details/', views.fee_details, name='fee_details'),
    path('income-report/', views.income_report, name='income_report'),
    path('expense-report/', views.expense_report, name='expense_report'),
    path('expenses/', views.expenses, name='expenses'), 
    path('fee-adding/', views.fee_adding, name='fee_adding'),
    path('logout/', views.admin_logout, name='admin_logout'),
    path('add_user/', views.add_user, name='add_user'),
    path('get_customers_data/', views.get_customers_data, name='get_customers_data'),
    path('edit_customer/<int:customer_id>/', views.edit_customer, name='edit_customer'),
    path('delete_customer/<int:customer_id>/', views.delete_customer, name='delete_customer'),
    path('get_expenses_data/', views.get_expenses_data, name='get_expenses_data'),
    path('add_expense/', views.add_expense, name='add_expense'),
    path('edit_expense/<int:expense_id>/', views.edit_expense, name='edit_expense'),
    path('delete_expense/<int:expense_id>/', views.delete_expense, name='delete_expense'),
    path('export-income/', views.export_income, name='export_income'),
    path('export-income-excel/', views.export_income_excel, name='export_income_excel'),
    path('get-income-data/', views.get_income_data, name='get_income_data'),
    path('export-expenses/', views.export_expenses, name='export_expenses'),
    path('export-expenses-excel/', views.export_expenses_excel, name='export_expenses_excel'),
    path('add-fee/', views.add_user, name='add_fee'),
    path('get-fee-data/', views.get_fees_data, name='get_fee_data'),
    path('fee/edit/<int:fee_id>/', views.edit_fee, name='edit_fee'),
    path('dashboard-data/', views.get_dashboard_data, name='get_dashboard_data'),
    path('manage-fees/', views.manage_fees, name='manage_fees'),
    path('get_packages/', views.get_packages, name='get_packages'),
    path('update-package-amount/', views.update_package_amount, name='update_package_amount'),
    path('profit-loss-report/', views.profit_loss_report, name='profit_loss_report'),
    path('fee-adding/', views.fee_adding, name='fee_adding'),
    path('get_fees_data/<int:customer_id>/', views.get_fees_data, name='get_fees_data'),
    path('fees/', views.fees_page, name='fees_page'),
    path('api/fees/alldata/', views.get_all_fees_data, name='get_all_fees_data'),
    path('api/fees/data/', views.get_fees_data, name='get_fees_data'),
    path('api/fees/update/', views.update_fee, name='update_fee'),
    path('api/fees/delete/<int:fee_id>/', views.delete_fee, name='delete_fee'),
    path('break-member/<int:customer_id>/', views.break_member, name='break_member'),
    path('unbreak-member/<int:customer_id>/', views.unbreak_member, name='unbreak_member'),
    path('send-whatsapp/', views.send_whatsapp, name='send_whatsapp'),
    path('add-next-month-fee/<str:customer_id>/', views.add_next_month_fee, name='add_next_month_fee'),
    path('send-overdue-notice/<int:customer_id>/', views.send_overdue_notice, name='send_overdue_notice'),
    path('generate-receipt/<int:customer_id>/', views.generate_receipt, name='generate_receipt'),
    path('payment_history/<int:fee_id>/', views.payment_history, name='payment_history'),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)